# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminLogin(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 313)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 80, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.UserEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.UserEntry.setGeometry(QtCore.QRect(220, 80, 113, 20))
        self.UserEntry.setObjectName("UserEntry")
        self.PassEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.PassEntry.setGeometry(QtCore.QRect(220, 120, 113, 20))
        self.PassEntry.setObjectName("PassEntry")
        self.ConfirmBut = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmBut.setGeometry(QtCore.QRect(240, 150, 75, 23))
        self.ConfirmBut.setObjectName("ConfirmBut")
        self.CancelBut = QtWidgets.QPushButton(self.centralwidget)
        self.CancelBut.setGeometry(QtCore.QRect(130, 150, 75, 23))
        self.CancelBut.setObjectName("CancelBut")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 442, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Admin Username:"))
        self.label_2.setText(_translate("MainWindow", "Admin Password:"))
        self.ConfirmBut.setText(_translate("MainWindow", "Confirm"))
        self.CancelBut.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminLogin()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
