# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CodeShare.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CodeShare(object):
    def setupUi(self, CodeShare):
        CodeShare.setObjectName("CodeShare")
        CodeShare.resize(457, 208)
        self.centralwidget = QtWidgets.QWidget(CodeShare)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 411, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.JoinCode = QtWidgets.QLabel(self.centralwidget)
        self.JoinCode.setGeometry(QtCore.QRect(160, 100, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.JoinCode.setFont(font)
        self.JoinCode.setObjectName("JoinCode")
        CodeShare.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CodeShare)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 457, 21))
        self.menubar.setObjectName("menubar")
        CodeShare.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CodeShare)
        self.statusbar.setObjectName("statusbar")
        CodeShare.setStatusBar(self.statusbar)

        self.retranslateUi(CodeShare)
        QtCore.QMetaObject.connectSlotsByName(CodeShare)

    def retranslateUi(self, CodeShare):
        _translate = QtCore.QCoreApplication.translate
        CodeShare.setWindowTitle(_translate("CodeShare", "CodeShare"))
        self.label.setText(_translate("CodeShare", "Share this code with your players:"))
        self.JoinCode.setText(_translate("CodeShare", "153267"))
        self.label.adjustSize()
        self.JoinCode.adjustSize()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CodeShare = QtWidgets.QCodeShare()
    ui = Ui_CodeShare()
    ui.setupUi(CodeShare)
    CodeShare.show()
    sys.exit(app.exec_())
