# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfirmLeague.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from LeagueView import Ui_LeagueView


class Ui_ConfirmLeague(object):
    def openLeagueView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LeagueView()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 130, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 170, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.YesBut = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openLeagueView())
        self.YesBut.setGeometry(QtCore.QRect(390, 200, 75, 23))
        self.YesBut.setObjectName("YesBut")
        self.NoBut = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: MainWindow.close())
        self.NoBut.setGeometry(QtCore.QRect(290, 200, 75, 23))
        self.NoBut.setObjectName("NoBut")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "League Name"))
        self.label_2.setText(_translate("MainWindow", "Is this the correct league?"))
        self.YesBut.setText(_translate("MainWindow", "Yes"))
        self.NoBut.setText(_translate("MainWindow", "No"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ConfirmLeague()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
