# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JoinTeam.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd

import Backend


class Ui_TeamJoiner(object):
    def incPlayerCount(self, teamSelection):
        data = pd.read_excel ('Data1.xlsx', 'ViewTeams') #place "r" before the path string to address special character, such as '\'. Don't forget to put the file name at the end of the path + '.xlsx'
        teamName = list(data['Team Name'])
        playerCount = list(data['Player Count'])
        for x in teamName:
            if teamSelection == x:
                print(playerCount[x])
    def setupUi(self, TeamJoiner):
        TeamJoiner.setObjectName("TeamJoiner")
        TeamJoiner.resize(560, 319)
        self.centralwidget = QtWidgets.QWidget(TeamJoiner)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 60, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.TeamList = QtWidgets.QComboBox(self.centralwidget)
        self.TeamList.setGeometry(QtCore.QRect(290, 130, 81, 21))
        self.TeamList.setObjectName("TeamList")
        teamName = Backend.teamNames()
        for x in teamName:
            self.TeamList.addItem(x)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 130, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Confirm = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.incPlayerCount(self.TeamList.currentText()))
        self.Confirm.setGeometry(QtCore.QRect(300, 180, 75, 23))
        self.Confirm.setObjectName("Confirm")
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(210, 180, 75, 23))
        self.Back.setObjectName("Back")
        TeamJoiner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TeamJoiner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 21))
        self.menubar.setObjectName("menubar")
        TeamJoiner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TeamJoiner)
        self.statusbar.setObjectName("statusbar")
        TeamJoiner.setStatusBar(self.statusbar)

        self.retranslateUi(TeamJoiner)
        QtCore.QMetaObject.connectSlotsByName(TeamJoiner)

    def retranslateUi(self, TeamJoiner):
        _translate = QtCore.QCoreApplication.translate
        TeamJoiner.setWindowTitle(_translate("TeamJoiner", "MainWindow"))
        self.label.setText(_translate("TeamJoiner", "Join a Team"))
        self.label_2.setText(_translate("TeamJoiner", "Select a Team"))
        self.Confirm.setText(_translate("TeamJoiner", "Confirm"))
        self.Back.setText(_translate("TeamJoiner", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TeamJoiner = QtWidgets.QMainWindow()
    ui = Ui_TeamJoiner()
    ui.setupUi(TeamJoiner)
    TeamJoiner.show()
    sys.exit(app.exec_())
