# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LeagueView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from AdminLogin import Ui_AdminLogin

from CodeShare import Ui_CodeShare


class Ui_LeagueView(object):
    def openCodeViewer(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CodeShare()
        self.ui.setupUi(self.window)
        self.window.show()
    def openAdminLogin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AdminLogin()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, LeagueView):
        LeagueView.setObjectName("LeagueView")
        LeagueView.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(LeagueView)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.InvitePlayers = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.openCodeViewer())
        self.InvitePlayers.setGeometry(QtCore.QRect(640, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InvitePlayers.setFont(font)
        self.InvitePlayers.setObjectName("InvitePlayers")
        self.Schedule = QtWidgets.QPushButton(self.centralwidget)
        self.Schedule.setGeometry(QtCore.QRect(310, 220, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Schedule.setFont(font)
        self.Schedule.setObjectName("Schedule")
        self.Rulebook = QtWidgets.QPushButton(self.centralwidget)
        self.Rulebook.setGeometry(QtCore.QRect(310, 140, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Rulebook.setFont(font)
        self.Rulebook.setObjectName("Rulebook")
        self.Standings = QtWidgets.QPushButton(self.centralwidget)
        self.Standings.setGeometry(QtCore.QRect(310, 300, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Standings.setFont(font)
        self.Standings.setObjectName("Standings")
        self.Teams = QtWidgets.QPushButton(self.centralwidget)
        self.Teams.setGeometry(QtCore.QRect(310, 380, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Teams.setFont(font)
        self.Teams.setObjectName("Teams")
        self.Logout = QtWidgets.QPushButton(self.centralwidget)
        self.Logout.setGeometry(QtCore.QRect(30, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Logout.setFont(font)
        self.Logout.setObjectName("Logout")
        self.CreateTeam = QtWidgets.QPushButton(self.centralwidget)
        self.CreateTeam.setGeometry(QtCore.QRect(640, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CreateTeam.setFont(font)
        self.CreateTeam.setObjectName("CreateTeam")
        self.Admin = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.openAdminLogin())
        self.Admin.setGeometry(QtCore.QRect(120, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Admin.setFont(font)
        self.Admin.setObjectName("Admin")
        LeagueView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LeagueView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        LeagueView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LeagueView)
        self.statusbar.setObjectName("statusbar")
        LeagueView.setStatusBar(self.statusbar)

        self.retranslateUi(LeagueView)
        QtCore.QMetaObject.connectSlotsByName(LeagueView)

    def retranslateUi(self, LeagueView):
        _translate = QtCore.QCoreApplication.translate
        LeagueView.setWindowTitle(_translate("LeagueView", "MainWindow"))
        self.label.setText(_translate("LeagueView", "League Name"))
        self.InvitePlayers.setText(_translate("LeagueView", "Invite Players"))
        self.Schedule.setText(_translate("LeagueView", "Schedule"))
        self.Rulebook.setText(_translate("LeagueView", "Rulebook"))
        self.Standings.setText(_translate("LeagueView", "Standings"))
        self.Teams.setText(_translate("LeagueView", "Teams"))
        self.Logout.setText(_translate("LeagueView", "Logout"))
        self.CreateTeam.setText(_translate("LeagueView", "Create a Team"))
        self.Admin.setText(_translate("LeagueView", "Admin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LeagueView = QtWidgets.QMainWindow()
    ui = Ui_LeagueView()
    ui.setupUi(LeagueView)
    LeagueView.show()
    sys.exit(app.exec_())
