# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LeagueConfirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LeagueConfirm(object):
    def setupUi(self, LeagueConfirm):
        LeagueConfirm.setObjectName("LeagueConfirm")
        LeagueConfirm.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(LeagueConfirm)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.LeagueName = QtWidgets.QLabel(self.centralwidget)
        self.LeagueName.setGeometry(QtCore.QRect(260, 90, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LeagueName.setFont(font)
        self.LeagueName.setObjectName("LeagueName")
        self.Username = QtWidgets.QLabel(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(260, 170, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Username.setFont(font)
        self.Username.setObjectName("Username")
        self.SportName = QtWidgets.QLabel(self.centralwidget)
        self.SportName.setGeometry(QtCore.QRect(260, 130, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SportName.setFont(font)
        self.SportName.setObjectName("SportName")
        self.Password = QtWidgets.QLabel(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(260, 220, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Password.setFont(font)
        self.Password.setObjectName("Password")
        self.ConfirmBut = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmBut.setGeometry(QtCore.QRect(390, 270, 75, 23))
        self.ConfirmBut.setObjectName("ConfirmBut")
        self.BackBut = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: LeagueConfirm.close())
        self.BackBut.setGeometry(QtCore.QRect(260, 270, 75, 23))
        self.BackBut.setObjectName("BackBut")
        LeagueConfirm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LeagueConfirm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        LeagueConfirm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LeagueConfirm)
        self.statusbar.setObjectName("statusbar")
        LeagueConfirm.setStatusBar(self.statusbar)

        self.retranslateUi(LeagueConfirm)
        QtCore.QMetaObject.connectSlotsByName(LeagueConfirm)

    def retranslateUi(self, LeagueConfirm):
        _translate = QtCore.QCoreApplication.translate
        LeagueConfirm.setWindowTitle(_translate("LeagueConfirm", "MainWindow"))
        self.label_2.setText(_translate("LeagueConfirm", "League Creator"))
        self.LeagueName.setText(_translate("LeagueConfirm", "League Name:" + Ui_CreateLeague.leagueName.line.text()))
        self.Username.setText(_translate("LeagueConfirm", "Admin Username:"+ Ui_CreateLeague.userName.line.text()))
        self.SportName.setText(_translate("LeagueConfirm", "Sport:"+ Ui_CreateLeague.selectedSport.line.text()))
        self.Password.setText(_translate("LeagueConfirm", "Admin Password:"+ Ui_CreateLeague.password.line.text()))
        self.ConfirmBut.setText(_translate("LeagueConfirm", "Confirm"))
        self.BackBut.setText(_translate("LeagueConfirm", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LeagueConfirm = QtWidgets.QMainWindow()
    ui = Ui_LeagueConfirm()
    ui.setupUi(LeagueConfirm)
    LeagueConfirm.show()
    sys.exit(app.exec_())
