# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LeagueFinder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from ConfirmLeague import Ui_ConfirmLeague
import Backend

class Ui_LeagueFinder(object):
    def openConfirmLeague(self, L, LeagueJoiner):
        try:
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_ConfirmLeague()
            self.ui.setupUi(self.window, L, LeagueJoiner)
            leagueName = Backend.league_Finder(int(self.CodeEntry.text()))
            self.ui.label.setText(leagueName)
            self.window.show()
            LeagueJoiner.hide()
        except:
            self.Infor.setText("Please check the input")

    def back_main(self, L, JoinLeague):
        L.show()
        JoinLeague.hide()

    def setupUi(self, JoinLeague, L):
        JoinLeague.setObjectName("JoinLeague")
        JoinLeague.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(JoinLeague)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 240, 171, 82))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CodeEntry = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.CodeEntry.setObjectName("CodeEntry")
        self.verticalLayout.addWidget(self.CodeEntry)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BackBut = QtWidgets.QPushButton(self.verticalLayoutWidget, clicked = lambda: self.back_main(L,JoinLeague))
        self.BackBut.setObjectName("BackBut")
        self.horizontalLayout.addWidget(self.BackBut)
        self.Search = QtWidgets.QPushButton(self.verticalLayoutWidget, clicked = lambda: self.openConfirmLeague(L, JoinLeague))
        self.Search.setObjectName("Search")
        self.horizontalLayout.addWidget(self.Search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 190, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.Infor = QtWidgets.QLabel(self.centralwidget)
        self.Infor.setGeometry(QtCore.QRect(290, 220, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Infor.setFont(font)
        self.Infor.setObjectName("label")

        JoinLeague.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JoinLeague)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        JoinLeague.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JoinLeague)
        self.statusbar.setObjectName("statusbar")
        JoinLeague.setStatusBar(self.statusbar)

        self.retranslateUi(JoinLeague)
        QtCore.QMetaObject.connectSlotsByName(JoinLeague)

    def retranslateUi(self, JoinLeague):
        _translate = QtCore.QCoreApplication.translate
        JoinLeague.setWindowTitle(_translate("JoinLeague", "MainWindow"))
        self.BackBut.setText(_translate("JoinLeague", "Back"))
        self.Search.setText(_translate("JoinLeague", "Search"))
        self.label.setText(_translate("JoinLeague", "Enter League Code"))
        self.Infor.setText(_translate("JoinLeague", ""))
        self.label.adjustSize()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JoinLeague = QtWidgets.QMainWindow()
    ui = Ui_LeagueFinder()
    ui.setupUi(JoinLeague)
    JoinLeague.show()
    sys.exit(app.exec_())
