# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LeagueFinder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LeagueFinder(object):
    def setupUi(self, JoinLeague):
        JoinLeague.setObjectName("JoinLeague")
        JoinLeague.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(JoinLeague)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 240, 171, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 200, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        JoinLeague.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JoinLeague)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        JoinLeague.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JoinLeague)
        self.statusbar.setObjectName("statusbar")
        JoinLeague.setStatusBar(self.statusbar)

        self.retranslateUi(JoinLeague)
        QtCore.QMetaObject.connectSlotsByName(JoinLeague)

    def retranslateUi(self, JoinLeague):
        _translate = QtCore.QCoreApplication.translate
        JoinLeague.setWindowTitle(_translate("JoinLeague", "MainWindow"))
        self.pushButton.setText(_translate("JoinLeague", "Search"))
        self.label.setText(_translate("JoinLeague", "Enter League Code"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JoinLeague = QtWidgets.QMainWindow()
    ui = Ui_LeagueFinder()
    ui.setupUi(JoinLeague)
    JoinLeague.show()
    sys.exit(app.exec_())
