# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LeagueCreator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from LeagueView import Ui_LeagueView


class Ui_CreateLeague(object):
    def LeagueConfirmation(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LeagueConfirm()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("LeagueCreator")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 10, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        Ui_CreateLeague.selectedSport = QtWidgets.QComboBox(self.centralwidget)
        self.selectedSport.setGeometry(QtCore.QRect(380, 130, 111, 21))
        self.selectedSport.setObjectName("selectedSport")
        self.selectedSport.addItem("")
        self.selectedSport.addItem("")
        self.selectedSport.addItem("")
        self.selectedSport.addItem("")
        self.selectedSport.addItem("")
        self.selectedSport.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 90, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        Ui_CreateLeague.leagueName = QtWidgets.QLineEdit(self.centralwidget)
        self.leagueName.setGeometry(QtCore.QRect(380, 90, 113, 20))
        self.leagueName.setObjectName("leagueName")
        Ui_CreateLeague.userName = QtWidgets.QLineEdit(self.centralwidget)
        self.userName.setGeometry(QtCore.QRect(380, 170, 113, 20))
        self.userName.setObjectName("userName")
        Ui_CreateLeague.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(380, 210, 113, 20))
        self.password.setObjectName("password")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(239, 170, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(249, 210, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.createLeague = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.LeagueConfirmation())
        self.createLeague.setGeometry(QtCore.QRect(410, 250, 75, 23))
        self.createLeague.setObjectName("createLeague")
        self.returnMain = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: MainWindow.close())
        self.returnMain.setGeometry(QtCore.QRect(260, 250, 75, 23))
        self.returnMain.setObjectName("returnMain")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "League Creator"))
        self.selectedSport.setItemText(0, _translate("MainWindow", "None Selected"))
        self.selectedSport.setItemText(1, _translate("MainWindow", "Soccer"))
        self.selectedSport.setItemText(2, _translate("MainWindow", "Kickball"))
        self.selectedSport.setItemText(3, _translate("MainWindow", "Tennis"))
        self.selectedSport.setItemText(4, _translate("MainWindow", "Dodgeball"))
        self.selectedSport.setItemText(5, _translate("MainWindow", "Ultimate Frisbee"))
        self.label_2.setText(_translate("MainWindow", "Select Sport"))
        self.label_3.setText(_translate("MainWindow", "League Name"))
        self.label_4.setText(_translate("MainWindow", "Admin Username"))
        self.label_5.setText(_translate("MainWindow", "Admin Password"))
        self.createLeague.setText(_translate("MainWindow", "Done"))
        self.returnMain.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_CreateLeague()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())




class Ui_LeagueConfirm(object):

    def openLeagueView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LeagueView()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, LeagueConfirm):
        LeagueConfirm.setObjectName("LeagueConfirm")
        LeagueConfirm.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(LeagueConfirm)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.LeagueName = QtWidgets.QLabel(self.centralwidget)
        self.LeagueName.setGeometry(QtCore.QRect(260, 90, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LeagueName.setFont(font)
        self.LeagueName.setObjectName("LeagueName")
        self.Username = QtWidgets.QLabel(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(260, 170, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Username.setFont(font)
        self.Username.setObjectName("Username")
        self.SportName = QtWidgets.QLabel(self.centralwidget)
        self.SportName.setGeometry(QtCore.QRect(260, 130, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SportName.setFont(font)
        self.SportName.setObjectName("SportName")
        self.Password = QtWidgets.QLabel(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(260, 220, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Password.setFont(font)
        self.Password.setObjectName("Password")
        self.ConfirmBut = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openLeagueView())
        self.ConfirmBut.setGeometry(QtCore.QRect(390, 270, 75, 23))
        self.ConfirmBut.setObjectName("ConfirmBut")
        self.BackBut = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: LeagueConfirm.close())
        self.BackBut.setGeometry(QtCore.QRect(260, 270, 75, 23))
        self.BackBut.setObjectName("BackBut")
        LeagueConfirm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LeagueConfirm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        LeagueConfirm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LeagueConfirm)
        self.statusbar.setObjectName("statusbar")
        LeagueConfirm.setStatusBar(self.statusbar)

        self.retranslateUi(LeagueConfirm)
        QtCore.QMetaObject.connectSlotsByName(LeagueConfirm)

    def retranslateUi(self, LeagueConfirm):
        _translate = QtCore.QCoreApplication.translate
        LeagueConfirm.setWindowTitle(_translate("LeagueConfirm", "MainWindow"))
        self.label_2.setText(_translate("LeagueConfirm", "League Creator"))
        self.LeagueName.setText(_translate("LeagueConfirm", "League Name: " + Ui_CreateLeague.leagueName.text()))
        self.Username.setText(_translate("LeagueConfirm", "Admin Username: "+ Ui_CreateLeague.userName.text()))
        self.SportName.setText(_translate("LeagueConfirm", "Sport: " + Ui_CreateLeague.selectedSport.currentText()))
        self.Password.setText(_translate("LeagueConfirm", "Admin Password: "+ Ui_CreateLeague.password.text()))
        self.ConfirmBut.setText(_translate("LeagueConfirm", "Confirm"))
        self.BackBut.setText(_translate("LeagueConfirm", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LeagueConfirm = QtWidgets.QMainWindow()
    ui = Ui_LeagueConfirm()
    ui.setupUi(LeagueConfirm)
    LeagueConfirm.show()
    sys.exit(app.exec_())

