# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tester.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

from LeagueCreator import Ui_CreateLeague
from LeagueFinder import Ui_LeagueFinder



class Ui_Leagues(object):
    def openLeagueCreator(self, main_w):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CreateLeague()
        self.ui.setupUi(self.window,main_w)
        self.window.show()
        L.hide()


    def openLeagueFinder(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LeagueFinder()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, L):
        L.setObjectName("L")
        L.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(L)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setFixedSize(800, 600)
        windowwidth = self.centralwidget.width()
        windowheight = self.centralwidget.height()
        #LeagueMaker Button
        self.LeagueMaker = QtWidgets.QPushButton(self.centralwidget,  clicked = lambda: self.openLeagueCreator(L))
        self.LeagueMaker.setGeometry(QtCore.QRect(int(windowwidth/2)-(windowwidth*0.2/2), 180, int(windowwidth*0.2), int(windowheight*0.06)))
        self.LeagueMaker.setObjectName("LeagueMaker")
        #LeagueViewer Button
        self.LeagueViewer = QtWidgets.QPushButton(self.centralwidget)
        self.LeagueViewer.setGeometry(QtCore.QRect(int(windowwidth/2)-(windowwidth*0.2/2), 360, int(windowwidth*0.2), int(windowheight*0.06)))
        self.LeagueViewer.setObjectName("LeagueViewer")

        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setFont(font)
        self.label.setGeometry(QtCore.QRect(int(windowwidth/2)-(windowwidth*0.4/2), 450, 250, 100))
        self.label.setText("         System Players \nOur Software Has No Ads")
        self.label.adjustSize()
        self.label.setObjectName("label")

        # LeagueJoiner_button
        self.LeagueJoiner = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openLeagueFinder())
        self.LeagueJoiner.setGeometry(QtCore.QRect(int(windowwidth/2)-(windowwidth*0.2/2), 270, int(windowwidth*0.2), int(windowheight*0.06)))
        self.LeagueJoiner.setObjectName("LeagueJoiner")
        #IM Made Ez Label
        self.Name_Label = QtWidgets.QLabel(self.centralwidget)
        self.Name_Label.setGeometry(QtCore.QRect(int(windowwidth/2)-(windowwidth*0.2/2), 100, int(windowwidth*0.2), int(windowheight*0.06)))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Name_Label.setFont(font)
        self.Name_Label.setObjectName("label_2")
        L.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(L)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        L.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(L)
        self.statusbar.setObjectName("statusbar")
        L.setStatusBar(self.statusbar)

        self.retranslateUi(L)
        QtCore.QMetaObject.connectSlotsByName(L)

    def retranslateUi(self, L):
        _translate = QtCore.QCoreApplication.translate
        L.setWindowTitle(_translate("L", "MainWindow"))
        self.LeagueMaker.setText(_translate("L", "Create a League"))
        self.LeagueViewer.setText(_translate("L", "View a League"))
        self.LeagueJoiner.setText(_translate("L", "Join a League"))
        self.Name_Label.setText(_translate("L", "IM Made EZ"))
        self.Name_Label.adjustSize()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    L = QtWidgets.QMainWindow()
    ui = Ui_Leagues()
    ui.setupUi(L)
    L.show()
    sys.exit(app.exec_())
