# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlayerSignup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from LeagueView import Ui_LeagueView


class Ui_PlayerSignup(object):
    def openLeagueView(self,L):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LeagueView()
        self.ui.setupUi(self.window,L)
        self.window.show()
    def setupUi(self, MainWindow,L):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 140, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 200, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 250, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.NameEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.NameEntry.setGeometry(QtCore.QRect(330, 150, 113, 20))
        self.NameEntry.setObjectName("NameEntry")
        self.GenderEntry = QtWidgets.QComboBox(self.centralwidget)
        self.GenderEntry.setGeometry(QtCore.QRect(350, 250, 69, 22))
        self.GenderEntry.setObjectName("GenderEntry")
        self.GenderEntry.addItem("")
        self.GenderEntry.addItem("")
        self.GenderEntry.addItem("")
        self.GenderEntry.addItem("")
        self.GenderEntry.setItemText(3, "")
        self.Age = QtWidgets.QSpinBox(self.centralwidget)
        self.Age.setGeometry(QtCore.QRect(340, 200, 42, 22))
        self.Age.setObjectName("Age")
        self.Back = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: MainWindow.close())
        self.Back.setGeometry(QtCore.QRect(270, 290, 75, 23))
        self.Back.setObjectName("Back")
        self.Confirm = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.openLeagueView(L))
        self.Confirm.setGeometry(QtCore.QRect(380, 290, 75, 23))
        self.Confirm.setObjectName("Confirm")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Player Signup"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.label_3.setText(_translate("MainWindow", "Age:"))
        self.label_4.setText(_translate("MainWindow", "Gender:"))
        self.GenderEntry.setItemText(0, _translate("MainWindow", "Female"))
        self.GenderEntry.setItemText(1, _translate("MainWindow", "Male"))
        self.GenderEntry.setItemText(2, _translate("MainWindow", "Non-Binary"))
        self.Back.setText(_translate("MainWindow", "Back"))
        self.Confirm.setText(_translate("MainWindow", "Confirm"))
        self.label_2.adjustSize()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_PlayerSignup()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
